version: "3"

services:
  integration-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: integration-test
    environment:
      - INTERVIEW_SERVER=http://interview-test-server:5000
    depends_on:
      - interview-test-server

  tax-calculator:
    build:
      context: .
      dockerfile: Dockerfile
      target: service
    depends_on:
      - interview-test-server

  interview-test-server:
    image: ptsdocker16/interview-test-server
    init: true
    restart: always
    ports:
      - 5000:5000
