version: "3"

services:
  # tax-calculator:
  #   image: form3tech/interview-accountapi:v1.0.0-46-gb3b6c766
  #   restart: on-failure
  #   depends_on:
  #     - interview-test-server
  #   environment:
  #     - VAULT_ADDR=http://vault:8200
  #   ports:
  #     - 8080:8080

  interview-test-server:
    image: ptsdocker16/interview-test-server
    init: true
    restart: always
    ports:
      - 5000:5000
